### ISSUE TITLE
Rewrite scroll sandbox example into functional components

### ISSUE THREAD

**Issue by tam-carre** [tam-carre/thestrongestluknight#15]
https://codesandbox.io/s/upbeat-sara-fqzpt?file=/src/App.js

Don't do it if you have better things to do, this is primarily to help me learn (keep the class code available somewhere)

**Comment by sleotta** [comment]
PR here: https://github.com/tam-carre/thestrongestluknight/pull/16

**Comment by tam-carre** [comment]
closed by https://github.com/tam-carre/thestrongestluknight/pull/16
