### ISSUE TITLE
Load fonts and crucial images before starting to render

### ISSUE THREAD

**Issue by tam-carre** [tam-carre/thestrongestluknight#4]
Also need to show some nice loader but first we need to figure out the best way to pre-load font and image assets before React renders components.

If someone wants to make suggestions on how best to do it in the current setup please make them here.

**Comment by sleotta** [comment]
re fonts, the standard way is use `link` elements with `rel=preload` and chuck them in the head. Since we have the index.html in the public folder this is easy enough without having to do anything fancy

You _can_ do the same for images, but thats a lot of bandwidth so possibly only do this for the important images

**Comment by tam-carre** [comment]
I'm not sure this is "blocking" enough. I'll have to try it later.

**Comment by tam-carre** [comment]
Googling around it does seem to be blocking. Crazy. I think only the header image needs to be preloaded.

**Comment by sleotta** [comment]
Its not strictly speaking blocking, but you can do something like

```
     const [hasLoadedImage, setHasLoadedImage] = React.useState(false);
     ...
      <link rel="preload" onLoad={() => setHasLoadedImage(true)} as="image" href="<some image>" />

      { hasLoadedImage ? <Page /> : <Spinner />}
```

IE while the things you're waiting for load, show a spinner or something. That said, we dont want terrible load times, so the less we preload the better.

**Comment by tam-carre** [comment]
Thanks for the elaboration.

**Comment by sleotta** [comment]
https://github.com/tam-carre/thestrongestluknight/pull/12/files

Here's a fun little component I whipped up (havent tested much, it's late here and I have work in the morning)

basically give it a bunch of things to preload and it'll tell you via functional child if everything has loaded.

**Comment by tam-carre** [comment]
closed by https://github.com/tam-carre/thestrongestluknight/pull/12/files
