### ISSUE TITLE
Springs jitter when at the edge of viewport

### ISSUE THREAD

**Issue by tam-carre** [tam-carre/thestrongestluknight#9]
https://user-images.githubusercontent.com/1331748/122211026-91be6880-cea6-11eb-8ba5-3566b9b7f8a8.mp4

must find a setting to make it not behave that way

**Comment by sleotta** [comment]
This is because you're attaching the ref to the element which is moving. Attaching it to a wrapping div will fix this. Gimme a few minutes and I'll make a PR

**Comment by tam-carre** [comment]
> This is because you're attaching the ref to the element which is moving. Attaching it to a wrapping div will fix this. Gimme a few minutes and I'll make a PR

Excellent. Thanks.

**Comment by sleotta** [comment]
https://github.com/tam-carre/thestrongestluknight/pull/11

PR here

**Comment by tam-carre** [comment]
Fixed by https://github.com/tam-carre/thestrongestluknight/pull/11
